# Generated by Django 3.2.8 on 2021-12-22 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arkapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(max_length=20)),
                ('img', models.ImageField(upload_to='picture')),
                ('desc', models.TextField()),
                ('date', models.IntegerField()),
            ],
        ),
    ]
